const core = require('@applitools/eyes-sdk-core')
const WDIOCheckSettings = require('./src/WDIOCheckSettings')
const {WDIOEyesClassic, WDIOEyesVisualGrid, WDIOEyesFactory} = require('./src/WDIOSpecializedEyes')
const LegacySelector = require('./src/LegacySelector')

exports.Eyes = WDIOEyesFactory
exports.EyesWDIO = WDIOEyesClassic
exports.EyesVisualGrid = WDIOEyesVisualGrid
exports.Target = WDIOCheckSettings
exports.WebdriverioCheckSettings = WDIOCheckSettings

exports.By = LegacySelector
exports.EyesScreenshot = core.EyesScreenshotNew
exports.StitchMode = core.StitchMode
exports.Logger = core.Logger
exports.ClassicRunner = core.ClassicRunner
exports.VisualGridRunner = core.VisualGridRunner
exports.Configuration = core.Configuration
exports.ConsoleLogHandler = core.ConsoleLogHandler
exports.FileLogHandler = core.FileLogHandler
exports.BatchInfo = core.BatchInfo
exports.BrowserType = core.BrowserType
exports.DeviceName = core.DeviceName
exports.ScreenOrientation = core.ScreenOrientation
exports.IosDeviceName = core.IosDeviceName
exports.IosScreenOrientation = core.IosScreenOrientation
exports.Region = core.Region
exports.MatchLevel = core.MatchLevel
exports.RectangleSize = core.RectangleSize
exports.AccessibilityLevel = core.AccessibilityLevel
exports.AccessibilityRegionType = core.AccessibilityRegionType
exports.AccessibilityMatchSettings = core.AccessibilityMatchSettings
exports.AccessibilityGuidelinesVersion = core.AccessibilityGuidelinesVersion
exports.AccessibilityRegionBySelector = core.AccessibilityRegionBySelector
exports.AccessibilityRegionByElement = core.AccessibilityRegionByElement
exports.ProxySettings = core.ProxySettings
