source 'https://rubygems.org'

gem 'faye-websocket'
gem 'eventmachine'
gem 'colorize'

group :development do
  gem 'rspec'
  gem 'guard-rspec'
  gem 'webdrivers' # pulls in selenium-webdriver & browser driver(s)
  gem 'pry-byebug'
end
