// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

const { Eyes, Target } = require('@applitools/eyes-selenium')
describe('hello world', function() {
  this.timeout(30000)
  let driver
  let vars
  let eyes
  let preRenderHook
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://selenium:4444/wd/hub').build()
    vars = {}
    eyes = new Eyes()
    eyes.setApiKey(process.env["APPLITOOLS_API_KEY"])
    await eyes.open(driver, "applitools-ext", "hello world")
  })
  afterEach(async function() {
    await driver.quit();
    eyes.abortIfNotClosed()
  })
  it('check window full', async function() {
    await driver.get("https://applitools.com/helloworld")
    await eyes.setViewportSize({ width: 1280, height: 800 })
    await eyes.check("check full page", Target.window().webHook(preRenderHook).fully(true))
    await eyes.close()
  })
  it('check element', async function() {
    await driver.get("https://applitools.com/helloworld")
    await eyes.setViewportSize({ width: 1280, height: 800 })
    await eyes.check("a button", Target.region(By.css("button")).webHook(preRenderHook))
    await eyes.close()
  })
})
