"use strict";
exports.__esModule = true;
var BrowserName;
(function (BrowserName) {
    BrowserName["CHROME"] = "chrome";
    BrowserName["FIREFOX"] = "firefox";
    BrowserName["IE_11"] = "ie";
    BrowserName["IE_10"] = "ie10";
    BrowserName["EDGE"] = "edge";
    BrowserName["EDGE_CHROMIUM"] = "edgechromium";
    BrowserName["EDGE_LEGACY"] = "edgelegacy";
    BrowserName["SAFARI"] = "safari";
    BrowserName["CHROME_ONE_VERSION_BACK"] = "chrome-one-version-back";
    BrowserName["CHROME_TWO_VERSIONS_BACK"] = "chrome-two-versions-back";
    BrowserName["FIREFOX_ONE_VERSION_BACK"] = "firefox-one-version-back";
    BrowserName["FIREFOX_TWO_VERSIONS_BACK"] = "firefox-two-versions-back";
    BrowserName["SAFARI_ONE_VERSION_BACK"] = "safari-one-version-back";
    BrowserName["SAFARI_TWO_VERSIONS_BACK"] = "safari-two-versions-back";
    BrowserName["EDGE_CHROMIUM_ONE_VERSION_BACK"] = "edgechromium-one-version-back";
    BrowserName["EDGE_CHROMIUM_TWO_VERSIONS_BACK"] = "edgechromium-two-versions-back";
})(BrowserName || (BrowserName = {}));
exports["default"] = BrowserName;
