MEASURE_CONCURRENCY=5 MEASURE_TESTS=1 MEASURE_STEPS=1 MEASURE_BROWSERS=1   yarn mocha --no-timeouts measurements.js
MEASURE_CONCURRENCY=5 MEASURE_TESTS=1 MEASURE_STEPS=5 MEASURE_BROWSERS=1   yarn mocha --no-timeouts measurements.js
MEASURE_CONCURRENCY=5 MEASURE_TESTS=1 MEASURE_STEPS=5 MEASURE_BROWSERS=5   yarn mocha --no-timeouts measurements.js
MEASURE_CONCURRENCY=5 MEASURE_TESTS=25 MEASURE_STEPS=1 MEASURE_BROWSERS=5   yarn mocha --no-timeouts measurements.js
MEASURE_CONCURRENCY=5 MEASURE_TESTS=25 MEASURE_STEPS=5 MEASURE_BROWSERS=1   yarn mocha --no-timeouts measurements.js
MEASURE_CONCURRENCY=5 MEASURE_TESTS=25 MEASURE_STEPS=5 MEASURE_BROWSERS=5   yarn mocha --no-timeouts measurements.js
